apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: todo
        image: 546921922638.dkr.ecr.ap-southeast-1.amazonaws.com/myjava-app:2
        ports:
        - containerPort: 8000
